---
baseurl : "http://devilsworksho.org/"
MetaDataFormat : "yaml"
canonifyurls : false
title : "Devils' Workshop"
theme : "dw"
permalinks:
    page: /:slug/
    post: /:slug/

indexes:
   category: "categories"
   tag: "tags"
   author: "author"

# disqusShortname: "rahul286"

params:
  Subtitle: "The Tech Community blog!"
  Logo: "http://devilsworkshop.org/files/2012/02/devils-workshop-logo.png"
  GithubRepoUrl: "https://github.com/rtCamp/devilsworkshop.org/"
  Devils:
      rahul.bansal:
          twitter: http://twitter.com/rahul286
          facebook: http://facebook.com/rahulb286
          avatar: http://www.gravatar.com/avatar/a9253565cd7a0a613c1147db0e66e6f0.jpg
      arunsathiya:
           realname: Arun Sathiya
           facebook: http://facebook.com/arun.sathiya
           twitter: http://twitter.com/_vrarun
           avatar: http://1.gravatar.com/avatar/78e8e836498a12735cecb435310996fa
           bio: Blogger at Devils’ Workshop, StrikeBuys. Owns Samsung Galaxy S3 I9300 with CM 11 nightly build. Proud Indian. Needs HSDPA. TVS Alumnus. Learning ECE at SASTRA

menu:
    primary:
        - Name: About Me
          Pre: "<i class='fa fa-fw fa-user'></i>"
          Url: "/about/"
        - Name: Blog
          Pre: "<i class='fa fa-fw fa-bullhorn'></i>"
          Url: "/post/"
        - Name: Work
          Pre: "<i class='fa fa-fw fa-star'></i>"
          Url: "/work/"
        - Name: Interviews
          Pre: "<i class='fa fa-fw fa-microphone'></i>"
          Url: "/interviews/"

    social:
        - Name: "Facebook"
          Pre: "<i class='fa fa-facebook-square'></i>"
          Url: "https://facebook.com/rahulb286"
        - Name: "Twitter"
          Pre: "<i class='fa fa-twitter-square'></i>"
          Url: "https://twitter.com/rahul286"
        - Name: "Github"
          Pre: "<i class='fa fa-github-square'></i>"
          Url: "https://github.com/rahul286"
        - Name: "RSS Feed"
          Pre: "<i class='fa fa-rss-square'></i>"
          Url: "/index.xml"
---
